### ISSUE TITLE
Question:  Fullscreen modal

### ISSUE THREAD

**Issue by ottigerb** [LukaszWatroba/v-modal#1]
@first - thanks for your work!  Is it possible to have also a 'fullscreen' size property?  100% width and height would be really nice!  Thanks

**Comment by LukaszWatroba** [comment]
I just added a `full` size property - width only. BUT you can add your own size in the config method e.g.:

``` js
angular
  .module('myApp', [ 'vModal' ])

  .config(function (modalConfig) {
    modalConfig.sizes.fullscreen = 'Dialog--sizeFullscreen'
  });
```

``` html
<v-modal>
  <v-dialog size="fullscreen">
    [content]
  </v-dialog>
</v-modal>
```

You can do the same with the position of the dialog and then add your own styles.
