### ISSUE TITLE
1.3.6 NPM version different from GitHub tag 1.3.6 ?

### ISSUE THREAD

**Issue by rossholdway** [LukaszWatroba/v-modal#18]
Hi

https://github.com/LukaszWatroba/v-modal/blob/v1.3.6/dist/v-modal.js is different to the version 1.3.6 pulled down with `npm install v-modal` ?

Specifically the npm version is missing `vModalDirective.$inject = ['$document', 'modalConfig'];`

Am I just missing something?

Thanks,
Ross

**Comment by LukaszWatroba** [comment]
Finally fixed.
Thank you Ross.
