### ISSUE TITLE
Pass some data on activate

### ISSUE THREAD

**Issue by gacha** [LukaszWatroba/v-modal#3]
Hi, I want to use some data in the template from the controller where I call `activate` method. How I see the `activate` method https://github.com/LukaszWatroba/v-modal/blob/master/dist/v-modal.js#L170 can receive some locals, but I can't figure out how can I access them in the template.

ps. thanks, for your work.

**Comment by LukaszWatroba** [comment]
Hey, I just solved the issue. Please, update vModal to the latest release - [v1.3.0](https://github.com/LukaszWatroba/v-modal/releases/tag/v1.3.0)

Example:

``` javascript
module.controller('MainController', function (loremModal) {
  var ctrl = this;

  var lorem = {
    title: 'Lorem ipsum dolor',
    content: 'Etiam ullamcorper.'
  };

  // Add params to the modal $scope
  ctrl.openLoremModal = function () {
    loremModal.activate(lorem);
  };
});
```

``` javascript
module.controller('LoremController', function ($scope, loremModal) {
  var ctrl = this;
  ctrl.close = loremModal.deactivate;
});
```

``` html
<v-modal class="vModal--default" onclose="loremModal.close()">
  <v-dialog large middle>
    <v-close label="Close"></v-close>

    <h3>{{ title }}</h3>
    <p>{{ content }}</p>
  </v-dialog>
</v-modal>
```

**Comment by gacha** [comment]
It works, thanks a lot.

**Comment by ik0r** [comment]
In this way, can I also pass function into modal controller, so I can invoke them in template like ng-click?

**Comment by LukaszWatroba** [comment]
@Treri I think you should use a custom event rather than pass a function into modal controller.
