### ISSUE TITLE
Should we listen to `$stateChangeStart` or `$routeChangeStart` to close modal automatically?

### ISSUE THREAD

**Issue by ik0r** [LukaszWatroba/v-modal#5]
If the modal is open, and user click back or forward button, the page is changed. but the modal is still open.
In this condition, maybe some methods or functions pointed to the page controller is not available no longer.
Should we listen to `$stateChangeStart` or `$routeChangeStart` to close modal automatically?

**Comment by LukaszWatroba** [comment]
The answer is YES. 

ui-router example:

``` js
$scope.$on('$stateChangeStart', function () {
    loginModal.deactivate();
});
```

**Comment by ik0r** [comment]
Thanks~

My meaning is should v-modal do this or user **themselves** who use v-moal do this.

**Comment by LukaszWatroba** [comment]
The reason is that there are several common routing libraries for AngulaJS and you can also do not use any of them in your project. It must be done manually.

**Comment by ik0r** [comment]
Yeah, thanks for your answer. :+1:
