### ISSUE TITLE
how can I close the modal in the controller

### ISSUE THREAD

**Issue by jeeeez** [LukaszWatroba/v-modal#6]
how can I close the modal in the controller

**Comment by LukaszWatroba** [comment]
You simply need to call `deactivate` method.

``` js
myApp.controller('MyController', function ($scope, myModal) {
  var ctrl = this;

  function closeMyModal () {
    myModal.deactivate();
  }

  ctrl.close = closeMyModal;
});
```

**Comment by jeeeez** [comment]
var myModal = vModal({
    controller:function($scope){
        $scope.close=function(){
        // I want to close this modal here.
        // Looking forward to your reply
        // thx
        }
    }
});

**Comment by LukaszWatroba** [comment]
@li2274221 please, take a look at the demo app module [here](https://github.com/LukaszWatroba/v-modal/blob/master/demo/app.js). I think you're doing something wrong.
